name: hello world workflow
on: [push]
jobs:
  say-hello:
    runs-on: ubantu-latest
    steps: 
      - name: checkout-repository
        uses: actions/checkout@v3

      - name: say hello
        uses: echo "Hello github actions"
